### PR TITLE
chore: Update eslint-plugin-logdna to 2.0.1

### PR DESCRIPTION
**Pull request by biblicalph**
Update plugin version to take advantage of the fix for require checks in expressions

Ref: #23

### CODE REVIEW

**Comment by esatterwhite** [comment]
@all-contributors please add @biblicalph  for maintenance

**Review by esatterwhite — APPROVED** [review]

**Comment by esatterwhite** [comment]
@all-contributors please add @biblicalph for maintenance

**Comment by esatterwhite** [comment]
https://github.com/all-contributors please add @biblicalph for maintenance, code

**Comment by esatterwhite** [comment]
@all-contributors please add @biblicalph for maintenance,code

**Comment by esatterwhite** [comment]
@all-contributors please add @biblicalph for maintenance, code

**Review by darinspivey — APPROVED** [review]

**Pull request merged**
